export const sideservices: string[] = [
    "Architecture",
    "Interior Design",
    "Product Design",
    "Event Planning",
    "Industrial Design",
    "Landscape Design",
    "Urban Planning",
    "Commercial Construction",
    "Residential Construction",
    "BIM (Building Information Management)",
    "Ordering, Cut Lists",
    "Bidding and Budget Modeling",
    "Project Management",
    "Infrastructure Construction",
    "Light Construction",
    "Remodeling",
    "Civil Engineering",
    "Mechanical Engineering",
    "Game Design",
    "Graphic Design",
    "Illustration",
    "Visualization",
    "Stage Design",
    "Film Design",
    "Medical Equipment Design",
    "Process Design",
    "Animation",
    "Presentations",
    "Sales and Marketing",
    "Surveying",
    "Government Planning",
    "Hi-Resolution Rendering",
    "3D Printing",
    "3D ART",
    "3D Modeling",
    "And more…"
];